Update readmes to reflect using go test instead of godog binary
elastic/e2e-testing pull request #1310
Opened 2021-07-01 15:55 UTC by adam-stokes

This updates the references to switching from the godog binary to using go test
exclusively. This makes the testing experience consistent across all operating
systems as godog will not compile on Windows but utilizing godog through go test
works as intended.

Signed-off-by: Adam Stokes <51892+adam-stokes@users.noreply.github.com>

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests (`make unit-test`), and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## How to test this PR locally

```
   cd e2e/_suites/fleet
   OP_LOG_LEVEL=DEBUG go test -v
```

## Related issues

- Fixes #1309

2021-07-01 16:00 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-1310/detail/PR-1310/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-1310/detail/PR-1310/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-1310/detail/PR-1310/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-1310/detail/PR-1310/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://e2e-testing_1310.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1310 opened`



* Start Time: 2021-07-01T15:55:22.080+0000


* Duration: 5 min 23 sec


* Commit: 6976bea5e32d37ae85d0cfaff4fa3d5365ee5a9c



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 19  |
| Skipped      | 0 |
| Total        | 19   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/PR-1310/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/PR-1310/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :green_heart: Flaky test report
Tests succeeded.


<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

### Test stats :test_tube:
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 19  |
| Skipped      | 0 |
| Total        | 19   |



</p>
</details>



<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-07-01 16:14 UTC, mdelapenya requested changes
LGTM, although I'd add the very same changes to the automation in place for CI execution. Please look at the `commons.mk` file, in the `functional-test` goal.

As we have the `TestMain` method in all test suites, I'd replace all executions of godog with this new approach.

Wdyt?

2021-07-06 16:31 UTC, adam-stokes commented on e2e/commons-test.mk
> +	go test -v --godog.format=${FORMAT} ${TAGS_FLAG}${TAGS_VALUE}
@mdelapenya I couldnt figure out if it was possible to just pass in a single features file this way, we may need to rethink if we want to support that feature or not or just stick to tags. wdyt?

2021-07-08 13:56 UTC, adam-stokes commented
jenkins test this please

2021-07-08 15:38 UTC, v1v approved these changes

2021-07-09 10:22 UTC, cachedout approved these changes

2021-07-09 13:16 UTC, merged