Changes done for adding windows integration script
elastic/e2e-testing pull request #3198
Opened 2022-11-07 13:14 UTC by dikshachauhan-qasource

## What does this PR do?
Adding windows integration successfully to a policy.

Hi @michalpristas 

Here, are the changes that I have made for above script. Below is the error that we are getting while adding this integration.

**Error logs:**
`level=warning msg="could not add package to policy because of HTTP code is not 200" elapsedTime=20.923285992s err="<nil>" package="{ windows-3324d79a-c85c-4fb5-8c24-67dce028698c Windows default 1f046770-5e8f-11ed-8358-77c1e5cff8c3 true  [{winlog true [{{metrics windows.powershell} true winlog-windows.powershell-3d8fd865-b8cc-4371-a891-5c52e7d05f4f map[period:{1s string}]}] map[] <nil> <nil>}] { windows Windows 1.15.0}}" response="{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"Package policy is invalid: inputs.winlog.streams.windows.powershell.vars.preserve_original_event: Preserve original event is required\\ninputs.winlog.streams.windows.powershell.vars.event_id: Event ID is required\"}" retry=7 statusCode=400`

2022-11-07 14:21 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://e2e-testing_3198.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-11-07T13:04:57.056Z&rangeTo=2022-11-07T13:24:57.056Z&transactionName=BUILD+e2e-tests%2Fe2e-testing-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=ecc02c8c17449fafd4956be926cdccf5&transactionId=f5bdc849ea4bc50c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-11-07T13:14:57.056+0000


* Duration: 66 min 18 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 215  |
| Skipped      | 0 |
| Total        | 216   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Initializing / Pre-Submit / Sanity checks / fix end of files – pre_commit.lint`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 error 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 ![CDATA[- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing e2e/_suites/fleet/testresources/windows.json

]] 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Start Elastic Stack`
<ul>
<li>Took 11 min 37 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-3198/runs/1/steps/564/log/?start=0">here</a></li>
<li>Description: <code>make -C .ci start-elastic-stack</code></l1>
</ul>
  
  </p>
  </details>



## :bug: Flaky test report
:grey_exclamation: There are test failures but not known flaky tests.



<details><summary>Expand to view the summary</summary>
<p>

### Genuine test errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/1//tests)
:broken_heart: There are test failures but not known flaky tests, most likely a genuine test failure.

* **Name**: `Initializing / Pre-Submit / Sanity checks / fix end of files – pre_commit.lint`

</p>
</details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-11-08 07:48 UTC, michalpristas approved these changes
please also paste `windows.json` into https://jsonlint.com/
to fix formatting and indentations to make it more readable

2022-11-08 07:48 UTC, michalpristas commented on e2e/_suites/fleet/testresources/windows.json
> +					"preserve_original_event": false,
```suggestion
                                        "preserve_original_event": {
                                            "type":"bool",
                                            "value": false
                                        },
```

2022-11-08 07:48 UTC, michalpristas commented on e2e/_suites/fleet/testresources/windows.json
> +					"preserve_original_event": false,
```suggestion
                                        "preserve_original_event": {
                                            "type":"bool",
                                            "value": false
                                        },
```

2022-11-08 07:48 UTC, michalpristas commented on e2e/_suites/fleet/testresources/windows.json
> +					"preserve_original_event": false,
```suggestion
                                        "preserve_original_event": {
                                            "type":"bool",
                                            "value": false
                                        },
```

2022-11-08 07:48 UTC, michalpristas commented on e2e/_suites/fleet/testresources/windows.json
> +					"preserve_original_event": false,
```suggestion
                                        "preserve_original_event": {
                                            "type":"bool",
                                            "value": false
                                        },
```

2022-11-08 07:48 UTC, michalpristas commented on e2e/_suites/fleet/testresources/windows.json
> +					"preserve_original_event": false,
```suggestion
                                        "preserve_original_event": {
                                            "type":"bool",
                                            "value": false
                                        },
```

2022-11-08 07:49 UTC, michalpristas requested changes
wrong button

2022-11-17 06:13 UTC, dikshachauhan-qasource commented
Hi @michalpristas 

I have reran the script after making the above suggested changes, however the issue still persists as reported.

Could you please recheck and let me know further inputs, that could work.

Thanks in Advance.

2022-11-22 14:40 UTC, michalpristas commented on e2e/_suites/fleet/testresources/windows.json
> +{
try this one
```json
{
	"inputs": [{
		"type": "winlog",
		"enabled": true,
		"streams": [
		  {
				"data_stream": {
					"type": "logs",
					"dataset": "windows.forwarded"
				},
				"vars": {
					"period": {
						"type": "text",
						"value": "10s"
					},
					"preserve_original_event": {
						"type": "bool",
						"value": false
					},
					"event_id": {
						"type": "text",
						"value": "some_id"
					},
					"tags": {
						"type": "text",
						"value": ["preserve_original_event", "forwarded", "microsoft_dhcp"]
					}
				},
				"id": "winlog-windows.forwarded-7886c582-c3fa-4ce1-a016-a6819dbba179",
				"enabled": true
			},
			{
				"data_stream": {
					"type": "logs",
					"dataset": "windows.powershell"
				},
				"vars": {
					"period": {
						"type": "text",
						"value": "10s"
					},
					"preserve_original_event": {
						"type": "bool",
						"value": false
					},
					"event_id": {
						"type": "text",
						"value": "some_id"
					},
					"tags": {
						"type": "text",
						"value": ["preserve_original_event", "forwarded", "microsoft_dhcp"]
					}
				},
					"id": "winlog-windows.powershell-7886c582-c3fa-4ce1-a016-a6819dbba179",
					"enabled": true
				
			},
			{
				"data_stream": {
					"type": "logs",
					"dataset": "windows.powershell_operational"
				},
				"vars": {
					"period": {
						"type": "text",
						"value": "10s"
					},
					"preserve_original_event": {
						"type": "bool",
						"value": false
					},
					"event_id": {
						"type": "text",
						"value": "some_id"
					},
					"tags": {
						"type": "text",
						"value": ["preserve_original_event", "forwarded", "microsoft_dhcp"]
					}
				},
				"id": "winlog-windows.powershell_operational-7886c582-c3fa-4ce1-a016-a6819dbba179",
				"enabled": true
			},
			{
				"data_stream": {
					"type": "logs",
					"dataset": "windows.sysmon_operational"
				},
				"vars": {
					"period": {
						"type": "text",
						"value": "10s"
					},
					"preserve_original_event": {
						"type": "bool",
						"value": false
					},
					"event_id": {
						"type": "text",
						"value": "some_id"
					},
					"tags": {
						"type": "text",
						"value": ["preserve_original_event", "forwarded", "microsoft_dhcp"]
					}
				},
				"id": "winlog-windows.sysmon_operational-7886c582-c3fa-4ce1-a016-a6819dbba179",
				"enabled": true
			},
			{
				"data_stream": {
					"type": "metrics",
					"dataset": "windows.perfmon"
				},
				"vars": {
					"period": {
						"type": "text",
						"value": "10s"
					},
					"preserve_original_event": {
						"type": "bool",
						"value": false
					},
					"event_id": {
						"type": "text",
						"value": "some_id"
					},
					"tags": {
						"type": "text",
						"value": ["preserve_original_event", "forwarded", "microsoft_dhcp"]
					}
				},
				"id": "windows/metrics-windows.perfmon-7886c582-c3fa-4ce1-a016-a6819dbba179",
				"enabled": true
			},
			{
				"data_stream": {
					"type": "metrics",
					"dataset": "windows.service"
				},
				"vars": {
					"period": {
						"type": "text",
						"value": "10s"
					},
					"preserve_original_event": {
						"type": "bool",
						"value": false
					},
					"event_id": {
						"type": "text",
						"value": "some_id"
					},
					"tags": {
						"type": "text",
						"value": ["preserve_original_event", "forwarded", "microsoft_dhcp"]
					}
				},
				"id": "windows/metrics-windows.service-7886c582-c3fa-4ce1-a016-a6819dbba179",
				"enabled": true
			}
		]
	}]
}
```

2023-01-09 12:58 UTC, closed without merging

2023-01-09 13:23 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/4//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/4//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/4//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/4//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://e2e-testing_3198.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2023-01-09T11:41:47.498Z&rangeTo=2023-01-09T12:01:47.498Z&transactionName=BUILD+e2e-tests%2Fe2e-testing-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=41ed47c3eb23664412fdae05ea13cb14&transactionId=c73efe4d1df28205)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-01-09T11:51:47.498+0000


* Duration: 91 min 16 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 14  |
| Passed       | 19  |
| Skipped      | 0 |
| Total        | 33   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![14](https://img.shields.io/badge/14%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/4//tests)
<details><summary>Expand to view the tests failures</summary><p>
    > Show only the first 10 test failures
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Deploying the agent – Fleet Mode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the "elastic-agent" process is in the "started" state on the host 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Deploying the agent including command line --tag for tags – Fleet Mode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the agent is listed in Fleet as "online" 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Restarting the installed agent – Fleet Mode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the "elastic-agent" process is "restarted" on the host 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Un-enrolling the agent deactivates the agent – Fleet Mode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the agent is un-enrolled 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Re-enrolling the agent activates the agent in Fleet – Fleet Mode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the agent is un-enrolled 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Revoking the enrollment token for the agent – Fleet Mode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the enrollment token is revoked 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Un-installing the installed agent – Fleet Mode`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the "elastic-agent" process is "uninstalled" on the host 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_upgrade_agent / Upgrading an installed agent from latest – Upgrade Agent`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step the agent is listed in Fleet as "online" 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_upgrade_agent / Upgrading an installed agent from 8.6.0 – Upgrade Agent`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step agent is in "latest" version: version mismatch required '8.6.0-SNAPSHOT' retrieved '8.6.0' 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
##### `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_upgrade_agent / Upgrading an installed agent from 8.5.3 – Upgrade Agent`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Step agent is in "latest" version: version mismatch required '8.6.0-SNAPSHOT' retrieved '8.5.3' 
 ```
</p></details>
<li>no stacktrace</li>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/4//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Run tests in the node`
<ul>
<li>Took 11 min 14 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-3198/runs/4/steps/1595/log/?start=0">here</a></li>
<li>Description: <code>make -C .ci run-tests</code></l1>
</ul>
  
  
  
  
##### `Run tests in the node`
<ul>
<li>Took 51 min 20 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-3198/runs/4/steps/1521/log/?start=0">here</a></li>
<li>Description: <code>make -C .ci run-tests</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-3198/runs/4/steps/2342/log/?start=0">here</a></li>
<li>Description: <code>Error 'hudson.AbortException: script returned exit code 2'</code></l1>
</ul>
  
  </p>
  </details>



## :bug: Flaky test report
:grey_exclamation: There are test failures but not known flaky tests.



<details><summary>Expand to view the summary</summary>
<p>

### Genuine test errors [![14](https://img.shields.io/badge/14%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-3198/detail/PR-3198/4//tests)
:broken_heart: There are test failures but not known flaky tests, most likely a genuine test failure.

* **Name**: `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Deploying the agent – Fleet Mode`
* **Name**: `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Deploying the agent including command line --tag for tags – Fleet Mode`
* **Name**: `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Restarting the installed agent – Fleet Mode`
* **Name**: `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Un-enrolling the agent deactivates the agent – Fleet Mode`
* **Name**: `Initializing / End-To-End Tests / fleet_ubuntu_22_04_amd64_fleet_mode / Re-enrolling the agent activates the agent in Fleet – Fleet Mode`
* **Name**: `Initializing / End-To-End Tests / fleet_ubuntu_22_04 [...]