chore(ci): cache docker images in packer
elastic/e2e-testing pull request #430
Opened 2020-11-09 18:08 UTC by mdelapenya

## What does this PR do?
It adds picklesdoc and golang docker images in Packer

## Why is it important?
It will reduce build time

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [x] Checked the new script returns the proper GO_VERSION

Paste here output logs discovered while creating this PR, such as stack traces or integration logs, or any other output you consider important to be shared with the team.
-->

## Follow-ups
Identify new images and push updates in the script.

Question: is it possible to run the clean-docker.sh script at packer time? If so, would it be too much size to cache all those images?

2020-11-09 18:42 UTC, elasticmachine commented
## :green_heart: Flaky test report
Tests succeeded.


<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

### Test stats :test_tube:
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 79  |
| Skipped      | 11 |
| Total        | 90   |




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_flaky.id-->

2020-11-09 18:42 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-430/detail/PR-430/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-430/detail/PR-430/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-430/detail/PR-430/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-430/detail/PR-430/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://e2e-testing_430.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #430 opened]`

* Start Time: 2020-11-09T18:08:59.708+0000

* Duration: 33 min 4 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 79  |
| Skipped      | 11 |
| Total        | 90   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->





<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2020-11-09 19:45 UTC, v1v requested changes

2020-11-09 19:45 UTC, v1v commented on .ci/packer_cache.sh
> +readonly GO_VERSION=$(cat ${_sdir}/../.go-version)
The script runs in the context of the workspace, therefore if .go-version is in the top level folder, you could simplify the _sdir 

```
 readonly GO_VERSION=$(cat .go-version)
```

2020-11-09 19:52 UTC, mdelapenya commented on .ci/packer_cache.sh
> +readonly GO_VERSION=$(cat ${_sdir}/../.go-version)
```suggestion
# shellcheck disable=SC1091
source /usr/local/bin/bash_standard_lib.sh

readonly GO_VERSION=$(cat .go-version)
```

2020-11-10 07:05 UTC, cachedout approved these changes

2020-11-10 14:28 UTC, kuisathaverat approved these changes

2020-11-10 15:19 UTC, mdelapenya commented
@kuisathaverat are we usually backporting packer cache scripts to the maintenance branches?

2020-11-10 16:01 UTC, kuisathaverat commented
> @kuisathaverat are we usually backporting packer cache scripts to the maintenance branches?

no, the script is only grabbed from the master so you do not need to backport the change

2020-11-10 16:03 UTC, merged