fix: notify build result only once
elastic/e2e-testing pull request #673
Opened 2021-01-28 11:18 UTC by mdelapenya

## What does this PR do?
It removes the call to `notifyBuildResult` from the cleanUp hook, merging its parameters into the final invocation.

We are also fixing the flaky analyser name, using base branch instead of always using master.

## Why is it important?
We detected two documents on Jenkins-Stats

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [ ] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ] Flaky parameters: are they correct?

2021-01-28 15:57 UTC, cachedout approved these changes

2021-01-28 18:57 UTC, mdelapenya commented
Shouldn't the `notifyBuildResult` step post a GH comment with the build result?

2021-01-29 09:08 UTC, v1v requested changes
This won't work for PRs, `whenTrue` and `whenFalse` conditions apply for the same

2021-01-29 09:29 UTC, mdelapenya commented
> This won't work for PRs, `whenTrue` and `whenFalse` conditions apply for the same

Thanks for the feedback! I refactored it to simplify the logic, explained in the main body

2021-01-29 09:45 UTC, kuisathaverat approved these changes

2021-01-29 09:45 UTC, v1v approved these changes

2021-01-29 09:49 UTC, elasticmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-673/detail/PR-673/2//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-673/detail/PR-673/2//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-673/detail/PR-673/2//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-673/detail/PR-673/2//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://e2e-testing_673.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #673 updated`



* * Start Time: 2021-01-29T09:28:55.411+0000


* Duration: 21 min 38 sec


* Commit: 3b0db16ae2bc54a8166f535ee85f995c537df904



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 3  |
| Passed       | 82  |
| Skipped      | 11 |
| Total        | 96   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![3](https://img.shields.io/badge/3%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-673/detail/PR-673/2//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Initializing / End-To-End Tests / ubuntu-18.04_fleet_agent_endpoint_integration / [empty] – TEST-fleet.xml`


<ul>
<li>no error details</li>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Test report file /var/lib/jenkins/workspace/e2e-tests_e2e-testing-mbp_PR-673/src/github.com/elastic/e2e-testing/outputs/TEST-fleet.xml was length 0 
 ```
</p></details>
</ul>
    
##### `Initializing / End-To-End Tests / ubuntu-18.04_fleet_stand_alone_agent / [empty] – TEST-fleet.xml`


<ul>
<li>no error details</li>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Test report file /var/lib/jenkins/workspace/e2e-tests_e2e-testing-mbp_PR-673/src/github.com/elastic/e2e-testing/outputs/TEST-fleet.xml was length 0 
 ```
</p></details>
</ul>
    
##### `Initializing / End-To-End Tests / ubuntu-18.04_fleet_fleet_mode_agent / [empty] – TEST-fleet.xml`


<ul>
<li>no error details</li>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Test report file /var/lib/jenkins/workspace/e2e-tests_e2e-testing-mbp_PR-673/src/github.com/elastic/e2e-testing/outputs/TEST-fleet.xml was length 0 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->







### Steps errors [![10](https://img.shields.io/badge/10%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp%2FPR-673/detail/PR-673/2//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
##### `Run functional tests for fleet:fleet_mode_agent`
<ul>
<li>Took 15 min 32 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/1628/log/?start=0">here</a></li>
<li>Description: <code>.ci/scripts/functional-test.sh "fleet" "fleet_mode_agent" "8.0.0-SNAPSHOT" "8.0.0-SNAPSHOT" </code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/2077/log/?start=0">here</a></li>
<li>Description: <code>[2021-01-29T09:48:32.292Z] Archiving artifacts
script returned exit code 2</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/2082/log/?start=0">here</a></li>
<li>Description: <code>[2021-01-29T09:48:33.312Z] Archiving artifacts
hudson.AbortException: script returned exit code 2</code></l1>
</ul>
  
  
  
  
##### `Run functional tests for fleet:agent_endpoint_integration`
<ul>
<li>Took 7 min 53 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/1633/log/?start=0">here</a></li>
<li>Description: <code>.ci/scripts/functional-test.sh "fleet" "agent_endpoint_integration" "8.0.0-SNAPSHOT" "8.0.0-SNAPSHOT" </code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/2023/log/?start=0">here</a></li>
<li>Description: <code>[2021-01-29T09:40:53.992Z] Archiving artifacts
script returned exit code 2</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/2033/log/?start=0">here</a></li>
<li>Description: <code>[2021-01-29T09:40:54.837Z] Archiving artifacts
hudson.AbortException: script returned exit code 2</code></l1>
</ul>
  
  
  
  
##### `Run functional tests for fleet:stand_alone_agent`
<ul>
<li>Took 7 min 54 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/1638/log/?start=0">here</a></li>
<li>Description: <code>.ci/scripts/functional-test.sh "fleet" "stand_alone_agent" "8.0.0-SNAPSHOT" "8.0.0-SNAPSHOT" </code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 1 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/2037/log/?start=0">here</a></li>
<li>Description: <code>[2021-01-29T09:40:55.859Z] Archiving artifacts
script returned exit code 2</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/2042/log/?start=0">here</a></li>
<li>Description: <code>[2021-01-29T09:40:56.703Z] Archiving artifacts
hudson.AbortException: script returned exit code 2</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/pipelines/PR-673/runs/2/steps/2080/log/?start=0">here</a></li>
<li>Description: <code>hudson.AbortException: script returned exit code 2</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-01-29T09:47:21.411Z] time="2021-01-29T09:47:19Z" level=warning msg="The Kibana instance is not healthy yet" elapsedTime=3m46.193580702s error="GET request failed with 503" retry=52 statusEndpoint="http://localhost:5601/status"
[2021-01-29T09:47:23.945Z] time="2021-01-29T09:47:23Z" level=warning msg="The Kibana instance is not healthy yet" elapsedTime=3m50.181341781s error="GET request failed with 503" retry=53 statusEndpoint="http://localhost:5601/status"
[2021-01-29T09:47:24.657Z] 
Stopping metri [...]

2021-01-29 09:52 UTC, merged